"use client";

import { ArrowLeft, ArrowRight, Check, Copy, FileText, Mail, Plus, Trash2, Upload, Users } from "lucide-react";
import { FormEvent, type ReactNode, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Button, Field, SelectField } from "@/components/ui/controls";
import { AppShell } from "@/features/shell/app-shell";
import styles from "./onboarding.module.css";

type Step = "details" | "organisation" | "team" | "deals" | "addresses";
type Member = { email: string; access: "VIEW" | "MANAGE" };
type Deal = { id: string; name: string; documents: string[] };
type State = { step: Step; user?: { name: string; phone: string; designation: string }; organisation?: { name: string; industry: string; employees: string }; members: Member[]; deals: Deal[] };
const STORAGE_KEY = "ccd-onboarding-v2";
const DEFAULT_STATE: State = { step: "details", members: [], deals: [] };
const STEPS: { id: Step; label: string }[] = [{ id: "details", label: "Your details" }, { id: "organisation", label: "Organisation" }, { id: "team", label: "Invite team" }, { id: "deals", label: "Create deals" }, { id: "addresses", label: "Deal emails" }];

export function OnboardingFlow() {
  const [state, setState] = useState<State>(DEFAULT_STATE); const [saveError, setSaveError] = useState(""); const topRef = useRef<HTMLDivElement>(null);
  useEffect(() => { try { const saved = localStorage.getItem(STORAGE_KEY); if (saved) queueMicrotask(() => setState({ ...DEFAULT_STATE, ...JSON.parse(saved) as State })); } catch { queueMicrotask(() => setSaveError("We could not restore your saved setup. You can continue from this step.")); } }, []);
  function commit(next: State) { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); setState(next); setSaveError(""); topRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); } catch { setSaveError("This step could not be saved. Check your browser storage and try again."); } }
  const current = STEPS.findIndex((step) => step.id === state.step);
  return <AppShell title="Set up your workspace" context="About 4 minutes · saved as you go" accountLabel={state.user?.name}><div className={styles.frame} ref={topRef}><nav className={styles.progress} aria-label="Sign-up progress">{STEPS.map((step, index) => <div className={index === current ? styles.current : index < current ? styles.complete : ""} key={step.id}><span>{index < current ? <Check size={14} aria-hidden /> : index + 1}</span><strong>{step.label}</strong></div>)}</nav>{saveError && <p className={styles.errorBanner} role="alert">{saveError}</p>}{state.step === "details" && <DetailsStep state={state} commit={commit} />}{state.step === "organisation" && <OrganisationStep state={state} commit={commit} />}{state.step === "team" && <TeamStep state={state} commit={commit} />}{state.step === "deals" && <DealsStep state={state} commit={commit} />}{state.step === "addresses" && <AddressesStep state={state} />}</div></AppShell>;
}

type Props = { state: State; commit: (next: State) => void };
function DetailsStep({ state, commit }: Props) {
  const [name, setName] = useState(state.user?.name ?? ""); const [phone, setPhone] = useState(state.user?.phone ?? ""); const [designation, setDesignation] = useState(state.user?.designation ?? ""); const [error, setError] = useState("");
  function submit(event: FormEvent) { event.preventDefault(); if (!name.trim() || !phone.trim() || !designation.trim()) return setError("Complete your name, phone number and designation to continue."); commit({ ...state, user: { name: name.trim(), phone: phone.trim(), designation: designation.trim() }, step: "organisation" }); }
  return <StepLayout index={1} title="Tell us who you are" note="We use these details to identify you to colleagues and on deal activity."><form onSubmit={submit}><Field name="name" label="Full name" autoComplete="name" value={name} onChange={(e) => setName(e.target.value)} /><Field name="phone" label="Phone number" type="tel" autoComplete="tel" placeholder="+44 7700 900000" value={phone} onChange={(e) => setPhone(e.target.value)} /><Field name="designation" label="Designation" placeholder="Investment Associate" value={designation} onChange={(e) => setDesignation(e.target.value)} />{error && <p className={styles.fieldError} role="alert">{error}</p>}<Button type="submit">Continue to organisation<ArrowRight size={17} aria-hidden /></Button></form></StepLayout>;
}

function OrganisationStep({ state, commit }: Props) {
  const [name, setName] = useState(state.organisation?.name ?? ""); const [industry, setIndustry] = useState(state.organisation?.industry ?? "private-equity"); const [employees, setEmployees] = useState(state.organisation?.employees ?? "11-50"); const [error, setError] = useState("");
  function submit(event: FormEvent) { event.preventDefault(); if (!name.trim()) return setError("Enter your organisation name to continue."); commit({ ...state, organisation: { name: name.trim(), industry, employees }, step: "team" }); }
  return <StepLayout index={2} title="Set up your organisation" note="This creates the shared home for your team and deals." back={() => commit({ ...state, step: "details" })}><form onSubmit={submit}><Field name="organisation" label="Organisation name" autoComplete="organization" value={name} onChange={(e) => setName(e.target.value)} /><div className={styles.fieldPair}><SelectField name="industry" label="Industry" value={industry} onChange={(e) => setIndustry(e.target.value)}><option value="private-equity">Private equity</option><option value="private-credit">Private credit</option><option value="venture-capital">Venture capital</option><option value="family-office">Family office</option><option value="advisory">Advisory</option><option value="other">Other</option></SelectField><SelectField name="employees" label="Number of employees" value={employees} onChange={(e) => setEmployees(e.target.value)}><option>1-10</option><option>11-50</option><option>51-200</option><option>201-500</option><option>501+</option></SelectField></div>{error && <p className={styles.fieldError} role="alert">{error}</p>}<Button type="submit">Continue to team<ArrowRight size={17} aria-hidden /></Button></form></StepLayout>;
}

function TeamStep({ state, commit }: Props) {
  const [rows, setRows] = useState<Member[]>(state.members.length ? state.members : [{ email: "", access: "VIEW" }]); const [error, setError] = useState("");
  function update(index: number, patch: Partial<Member>) { setRows(rows.map((row, i) => i === index ? { ...row, ...patch } : row)); }
  function next(event: FormEvent) { event.preventDefault(); const members = rows.filter((row) => row.email.trim()); if (members.some((row) => !/^\S+@\S+\.\S+$/.test(row.email))) return setError("Check each team member’s email address."); commit({ ...state, members, step: "deals" }); }
  return <StepLayout index={3} title="Bring your deal team in" note="View can inspect deal records. Manage can add sources, invite people and approve changes." back={() => commit({ ...state, step: "organisation" })}><form onSubmit={next}><div className={styles.inviteRows}>{rows.map((row, index) => <div className={styles.inviteRow} key={index}><Field name={`member-${index}`} label="Work email" type="email" placeholder="colleague@firm.com" value={row.email} onChange={(e) => update(index, { email: e.target.value })} /><SelectField name={`access-${index}`} label="Deal rights" value={row.access} onChange={(e) => update(index, { access: e.target.value as Member["access"] })}><option value="VIEW">View</option><option value="MANAGE">Manage</option></SelectField><Button type="button" variant="ghost" aria-label={`Remove team member ${index + 1}`} onClick={() => setRows(rows.filter((_, i) => i !== index))}><Trash2 size={17} aria-hidden />Remove</Button></div>)}</div><Button type="button" variant="secondary" onClick={() => setRows([...rows, { email: "", access: "VIEW" }])}><Plus size={17} aria-hidden />Add team member</Button>{error && <p className={styles.fieldError} role="alert">{error}</p>}<div className={styles.formActions}><Button type="submit">Continue to deals<ArrowRight size={17} aria-hidden /></Button><Button type="button" variant="ghost" onClick={() => commit({ ...state, members: [], step: "deals" })}>Skip for now</Button></div></form></StepLayout>;
}

function DealsStep({ state, commit }: Props) {
  const [deals, setDeals] = useState<Deal[]>(state.deals.length ? state.deals : [{ id: "first-deal", name: "", documents: [] }]); const [error, setError] = useState("");
  function updateFiles(id: string, files: FileList | null) { if (!files) return; setDeals(deals.map((deal) => deal.id === id ? { ...deal, documents: [...new Set([...deal.documents, ...Array.from(files, (file) => file.name)])] } : deal)); }
  function submit(event: FormEvent) { event.preventDefault(); if (!deals.length || deals.some((deal) => !deal.name.trim())) return setError("Name each deal before continuing."); commit({ ...state, deals: deals.map((deal) => ({ ...deal, name: deal.name.trim() })), step: "addresses" }); }
  return <StepLayout index={4} title="Create your first deals" note="Upload the baseline documents that define each diligence record. You can add more later." back={() => commit({ ...state, step: "team" })}><form onSubmit={submit} className={styles.dealForm}><div className={styles.dealRows}>{deals.map((deal, index) => <section className={styles.dealRow} key={deal.id}><header><strong>Deal {index + 1}</strong>{deals.length > 1 && <Button type="button" variant="ghost" onClick={() => setDeals(deals.filter((item) => item.id !== deal.id))}><Trash2 size={17} aria-hidden />Remove deal</Button>}</header><Field name={`deal-${deal.id}`} label="Deal name" placeholder="Project Atlas" value={deal.name} onChange={(e) => setDeals(deals.map((item) => item.id === deal.id ? { ...item, name: e.target.value } : item))} /><label className={styles.upload}><span><Upload size={20} aria-hidden /><strong>Upload documents</strong><small>PDF, Excel, CSV or text · select multiple files</small></span><input type="file" multiple accept=".pdf,.xlsx,.xls,.csv,.txt" onChange={(e) => updateFiles(deal.id, e.target.files)} /></label>{deal.documents.length > 0 && <ul className={styles.files}>{deal.documents.map((file) => <li key={file}><FileText size={16} aria-hidden /><span>{file}</span><button type="button" aria-label={`Remove ${file}`} onClick={() => setDeals(deals.map((item) => item.id === deal.id ? { ...item, documents: item.documents.filter((name) => name !== file) } : item))}>Remove</button></li>)}</ul>}</section>)}</div><Button type="button" variant="secondary" onClick={() => setDeals([...deals, { id: crypto.randomUUID(), name: "", documents: [] }])}><Plus size={17} aria-hidden />Add another deal</Button>{error && <p className={styles.fieldError} role="alert">{error}</p>}<Button type="submit">Create deals and continue<ArrowRight size={17} aria-hidden /></Button></form></StepLayout>;
}

function AddressesStep({ state }: { state: State }) {
  const router = useRouter(); const [copied, setCopied] = useState(""); const alias = (deal: Deal) => `${deal.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "deal"}@inbound.ccd.app`;
  async function copy(value: string) { await navigator.clipboard.writeText(value); setCopied(value); setTimeout(() => setCopied(""), 1600); }
  function finish() { localStorage.setItem("ccd-onboarding-complete", "true"); router.push("/dashboard"); }
  return <StepLayout index={5} title="Every deal now has an inbox" note="Forward or CC future correspondence to the matching address. CC’d will route it to the right deal."><div className={styles.addresses}>{state.deals.map((deal) => { const email = alias(deal); return <section key={deal.id}><Mail size={22} aria-hidden /><div><strong>{deal.name}</strong><code>{email}</code><small>{deal.documents.length} baseline document{deal.documents.length === 1 ? "" : "s"} added</small></div><Button type="button" variant="secondary" onClick={() => copy(email)}><Copy size={16} aria-hidden />{copied === email ? "Copied" : "Copy"}</Button></section>; })}</div><aside className={styles.routingNote}><Users size={20} aria-hidden /><p><strong>Keep the whole thread together.</strong> Team members with manage rights can add documents and approve proposed tracker changes.</p></aside><Button type="button" onClick={finish}>Go to all requests<ArrowRight size={17} aria-hidden /></Button></StepLayout>;
}

function StepLayout({ index, title, note, back, children }: { index: number; title: string; note: string; back?: () => void; children: ReactNode }) { return <section className={styles.step}><div className={styles.stepNote}><span>Step {index} of 5</span><h2>{title}</h2><p>{note}</p>{back && <button type="button" onClick={back}><ArrowLeft size={16} aria-hidden />Back</button>}</div><div className={styles.formSurface}>{children}</div></section>; }
